### ISSUE TITLE
Classiification map visualization issues

### ISSUE THREAD

**Issue by jilaniw** [AnkurDeria/MFT#10]
Hi, your work is awesome. i tried to run your code over disjoint datasets which worked great. The only thing is how to create classification maps visualization for these disjoint data sets like shown in your transaction? Please help it will be great favor. The link you sahred  in other issues for guidance is for single modal but for Multimodal like yours please share code.

**Comment by AnkurDeria** [comment]
Kindly check issue #7. For input maps, just use the multimodal data separately as in a separate map for HSI and LiDAR data. For output maps, the model output is mapped, so it's not really multimodal.

**Comment by jilaniw** [comment]
Thanks for your reply, but the source cited in issue # 7 also does not generate results like yours. Please, kindly provide your own code at ghulamjilaniw@gmail.com which can generate results cited as in fig. 9. It shall be greatest favor. 
Regards
![Transaction_UH_Class_Map](https://github.com/user-attachments/assets/b15c633e-e74b-4e65-b218-0aaefadb617a)

**Comment by lambda-wqi** [comment]
> Thanks for your reply, but the source cited in issue # 7 also does not generate results like yours. Please, kindly provide your own code at [ghulamjilaniw@gmail.com](mailto:ghulamjilaniw@gmail.com) which can generate results cited as in fig. 9. It shall be greatest favor. Regards ![Transaction_UH_Class_Map](https://github.com/user-attachments/assets/b15c633e-e74b-4e65-b218-0aaefadb617a)

Could  you please share your generating classfication map code?
