### ISSUE TITLE
How to run the program on 2018 Houston and Lidar ?

### ISSUE THREAD

**Issue by HarshAditya23** [AnkurDeria/MFT#2]
Tried to use on 2018 data but getting shape error.

Can you help in converting 2018 IEEE data in 11x11 disjoint data??

**Comment by AnkurDeria** [comment]
Thanks for your interest and I can suggest you to check the following github code for your solution https://github.com/gokriznastic/HybridSN/blob/master/HybridSN_V1.ipynb
