### ISSUE TITLE
Visualization problems?

### ISSUE THREAD

**Issue by fangwei00-jin** [AnkurDeria/MFT#3]
I'd like to know how did you visualize the disjoint data.

**Comment by AnkurDeria** [comment]
Select respective pixels(training and testing, in separate tensors) from the original data and mark everything else as background. Select 3 bands from all the bands. Set colours for the pixels according to their classes. Save the result as image.

**Comment by terigenbuaa** [comment]
There is only class number in the Houston Dataset but not the real land use class. I want to know which number in the label corresponds to which land-use category name. Could you provide any help? It would be really helpful, Thanks!

**Comment by xlsayhi** [comment]
> Select respective pixels(training and testing, in separate tensors) from the original data and mark everything else as background. Select 3 bands from all the bands. Set colours for the pixels according to their classes. Save the result as image.

hi, would you please help explain which python lib you use to visualize  the classification maps? e.g. Fig 11.

**Comment by AnkurDeria** [comment]
matplotlib
