### ISSUE TITLE
final results visualization 

### ISSUE THREAD

**Issue by tyust-dayu** [AnkurDeria/MFT#7]
Can you tell me how the final visualisation was done,  similar to the final visualisation in Figure 9, thank you very much! Can you provide me with your code, I would greatly appreciate it!

![image](https://github.com/AnkurDeria/MFT/assets/84608700/b67994f1-f4e7-4fac-9ace-a30ebaa9c10e)

**Comment by AnkurDeria** [comment]
You let the model classify the background pixels (no gt pixels) into the classes it was trained on by passing the entire image, including the background pixels. Then you assign a separate color to each class.

**Comment by HandsomebrotherA** [comment]
Hello, thank you for your generosity open source, do you have any code, I tried several times and couldn't make a visualization that works as well as yours

**Comment by AnkurDeria** [comment]
Kindly take a look at this repository: https://github.com/swalpa/Classification-of-Hyperspectral-Image
